import os,sys

class CustomException(Exception):
    def __init__(self,error_message:Exception,error_details:sys):
        self.error_message = CustomException
        pass



    def get_detailed_error_message(error_message:Exception,error_details:sys)->str:
        pass



